### ISSUE TITLE
Xiaomi 제습기 추가 가능할까요?

### ISSUE THREAD

**Issue by noogugae** [dugurs/lovelace-fan-xiaomi-miot#1]
Xiomi 제습기를 추가하고 싶어서 좀 건드려 봤는데 잘 안되네요.
혹시 추가가 가능할까요?
이 제품이구요.
https://home.miot-spec.com/spec/dmaker.derh.22l

아래처럼 code추가했는데 계속 기본 fan으로 나오네요.
그리고 ~.js fo;e 변경하면 새로 고침하면 되나요? 아님 재부팅을 해야 하나요?
요거 건드려 보는게 처음이라.

# this.model에 추가

      dmaker_derh_22l: {
        power: {
          prop: 'humidifier.on',
          value: false,
          state: ['off', 'on'],
          icon: ['mdi:air-humidifier-off','mdi:air-humidifier'],
          label: 'humidifier.target_humidity'
        },
        down: {
          prop: 'humidifier.target_humidity',
          value: 1,
          min: 40,
          max: 70,
          step: 1,
          icon: 'mdi:chevron-down',
          backward: true
        },
        up: {
          prop: 'humidifier.target_humidity',
          value: 1,
          min: 40,
          max: 70,
          step: 1,
          icon: 'mdi:chevron-up',
        },
        slider: {
          prop: 'humidifier.target_humidity',
          value: 1,
          min: 40,
          max: 70,
          step: 1
        },
        mode: {
          prop: 'humidifier.mode',
          value: [0,1],
          state: ['Smart', 'Sleep', 'Clothes Drying'],
          icon: ['mdi:waves','mdi:sleep','mdi:tshirt-crew-outline'],
        },
        fault: {
          prop: 'humidifier.fault',
          value: [0,1,2,3,4,5,6,7,8,9],
          state: ['No Faults', 'Water Full', 'Sensor Fault1', 'Sensor Fault2', 'Communication Fault1', 'Filter Clean', 'Defrost', 'Fan Motor', 'Overload', 'Lack Of Refrigerant'],
          icon: ['mdi:tray-full','mdi:alert-circle-check-outline','mdi:alert-circle-check', 'mdi:access-point-network-off', 'mdi:air-filter', 'mdi:car-defrost-rear', 'mdi:engine-off-outline', 'mdi:debug-step-over', 'mdi:gas-cylinder' ],
          click: ''
        },
        indicator_light: {
          prop: 'indicator_light.on',
          value: false,
          state: ['off', 'on'],
          icon: ['mdi:brightness-2','mdi:brightness-5']
        },
        alarm: {
          prop: 'alarm',
          value: false,
          state: ['off', 'on'],
          icon: ['mdi:volume-off','mdi:volume-high']
        },
        temperature: {
          prop: 'environment.temperature',
          value: 1,
          icon: 'mdi:thermometer',
          click: ''
        },
        humidity: {
          prop: 'environment.relative_humidity',
          value: 1,
          icon: 'mdi:water-percent',
          click: ''
        },
      }  

# ha card에 추가
      ha-card.dmaker_derh_22l {
        grid-template-columns: var(--card--grid-columns, repeat(5, 1fr));
        grid-template-areas: var(--card--grid-areas, "p s n n n " "m t h f a");
      }

**Comment by dugurs** [comment]
추가하였습니다.
hacs로 설치 하셨다면 업데이트 직후 알림창에서 리로드 눌러 주시면 적용됩니다.
모바일로 업데이트하고 리로드 해주시고, 컴에서는 `ctrl+shift+r` 로 해주세요.
오작동있으면 알려주세요.

**Comment by noogugae** [comment]
> 추가하였습니다. hacs로 설치 하셨다면 업데이트 직후 알림창에서 리로드 눌러 주시면 적용됩니다. 모바일로 업데이트하고 리로드 해주시고, 컴에서는 `ctrl+shift+r` 로 해주세요. 오작동있으면 알려주세요.

장염에 걸려서 추가해주셨는데 확인이 늦었습니다.
update후 확인해봤는데  요렇게 아래쪽에 시계모양 icon이 나타나네요. 
mdi imgae상 camare-timer이고 이러면 off-delay-time인거 같고 이거는 'o'인데 area에 정의 되지 않았는데 보이네요.

     ha-card.dmaker_derh_22l {
        grid-template-columns: var(--card--grid-columns, repeat(5, 1fr));
        grid-template-areas: var(--card--grid-areas, "p n n n n" "s m df f a");
      }

혹시 정의되면 무조건 보이게 되어 있나요?

![image](https://github.com/dugurs/lovelace-fan-xiaomi-miot/assets/74414408/380692bb-22d8-4ba0-a7d3-6e3224fc9301)

제가 좀 수정해서 맞춘 다음에 pull request로 해볼까 했는데 제가 code 수정 후에 아무리 강제 새로고침해도 변경되지가 않습니다.
HACS로 설치해둔 상태인데 제가 code 수정해서 적용되는 걸 확인하려면 어떻게 해야 할까요?

**Comment by dugurs** [comment]
> 혹시 정의되면 무조건 보이게 되어 있나요?

맞습니다. 지정하지 않고 숨기려면 css에서 display:none으로 저정하던가 해야 합니다.
areas에 포함시켰어야 했는데 빼먹었네요. 
수정해 올렸습니다.

> 제가 좀 수정해서 맞춘 다음에 pull request로 해볼까 했는데 제가 code 수정 후에 아무리 강제 새로고침해도 변경되지가 않습니다. HACS로 설치해둔 상태인데 제가 code 수정해서 적용되는 걸 확인하려면 어떻게 해야 할까요?

아마, 설치 폴더안에 gz파일을 지우고 새로고침 해보시면 수정한것 적용이 될겁니다.
